version: "3.9"

services:
  # =============================================================================
  # DATABASE SERVICE (PRODUCTION)
  # =============================================================================
  postgres:
    image: postgres:15-alpine
    container_name: ${PROJECT_SLUG}_postgres
    platform: linux/arm64
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      TZ: ${TIMEZONE:-UTC}
    ports:
      - "127.0.0.1:${POSTGRES_PORT_EXTERNAL:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/backup:/backup
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # =============================================================================
  # BACKEND SERVICE (STRAPI) - PRODUCTION
  # =============================================================================
  backend:
    container_name: ${PROJECT_SLUG}_backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/backend/production/Dockerfile
      target: production
    platform: linux/arm64
    expose:
      - "1337"
    volumes:
      - strapi_uploads:/app/public/uploads
    environment:
      # Database Configuration
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL:-true}
      
      # Strapi Configuration
      NODE_ENV: production
      STRAPI_HOST: 0.0.0.0
      STRAPI_PORT: 1337
      STRAPI_URL: ${STRAPI_URL}
      
      # Strapi Security
      STRAPI_ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      STRAPI_JWT_SECRET: ${ENCRYPTION_KEY}
      STRAPI_API_TOKEN_SALT: ${API_TOKEN_SALT}
      STRAPI_APP_KEYS: ${APP_KEYS}
      STRAPI_TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      STRAPI_CORS_ORIGIN: ${STRAPI_CORS_ORIGIN}
      
      # Timezone
      TZ: ${TIMEZONE:-UTC}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # =============================================================================
  # FRONTEND SERVICE (NEXTJS) - PRODUCTION
  # =============================================================================
  frontend:
    container_name: ${PROJECT_SLUG}_frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/frontend/production/Dockerfile
      target: production
    platform: linux/arm64
    expose:
      - "3000"
    environment:
      # Next.js Configuration
      NODE_ENV: production
      NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_STRAPI_URL: ${NEXT_PUBLIC_STRAPI_URL}
      
      # Analytics
      NEXT_PUBLIC_GOOGLE_ANALYTICS: ${NEXT_PUBLIC_GOOGLE_ANALYTICS}
      NEXT_PUBLIC_GOOGLE_TAG_MANAGER: ${NEXT_PUBLIC_GOOGLE_TAG_MANAGER}
      
      # Timezone
      TZ: ${TIMEZONE:-UTC}
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # =============================================================================
  # REVERSE PROXY (NGINX) - PRODUCTION
  # =============================================================================
  nginx:
    container_name: ${PROJECT_SLUG}_nginx
    restart: unless-stopped
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT_EXTERNAL:-80}:80"
      - "${NGINX_SSL_PORT_EXTERNAL:-443}:443"
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # =============================================================================
  # MONITORING SERVICES (PRODUCTION)
  # =============================================================================
  prometheus:
    container_name: ${PROJECT_SLUG}_prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./docker/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  grafana:
    container_name: ${PROJECT_SLUG}_grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${GRAFANA_PORT:-3001}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_DOMAIN: ${GRAFANA_DOMAIN:-localhost}
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # =============================================================================
  # BACKUP SERVICE (PRODUCTION)
  # =============================================================================
  backup:
    container_name: ${PROJECT_SLUG}_backup
    image: postgres:15-alpine
    restart: "no"
    volumes:
      - ./docker/backup:/backup
      - pgdata:/var/lib/postgresql/data:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: >
      sh -c "
        pg_dump -h postgres -U $${POSTGRES_USER} -d $${POSTGRES_DB} > /backup/backup_$$(date +%Y%m%d_%H%M%S).sql &&
        find /backup -name 'backup_*.sql' -mtime +${BACKUP_RETENTION_DAYS:-7} -delete
      "
    networks:
      - app-network

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  pgdata:
    driver: local
  strapi_uploads:
    driver: local
  nginx_logs:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 